export const action = {
  SET_PAGELOADDONE: 'setPageLoadDone',
  SET_LOADINGANIMATIONDONE: 'setLoadingAnimationDone',
  SET_LOCOMOTIVESCROLLDONE: 'setLocomotiveScrollDone',
  SET_PAGESLOADFINISHED: 'setPagesLoadFinished',
  SET_PAGE_TRANSITION_AFTER_ENTER: 'setPageTransitionAfterEnter',
  SET_INDEXPAGE: 'setIndexPage',
  SET_SCREENWIDTH: 'setScreenWidth',
  SET_SCREENSCROLL: 'setScreenScroll',
  SET_SCREENSCROLLDOWN: 'setScreenScrollDown',
  SET_SCREENSCROLLUP: 'setScreenScrollUp',
  SET_SCREENTOUCHDOWN: 'setScreenTouchDown',
  SET_SCREENRESIZE: 'setScreenResize',
  SET_AFTERSCREENRESIZE: 'setAfterScreenResize',
  SET_PAGEFOCUS: 'setPageFocus',
  SET_PAGELOADING: 'setPageLoading',
  SET_MEDIA: 'setMedia',
  SET_MEDIATEMP: 'setMediaTemp',
  SET_HTMLCSSVAR: 'setHtmlCssVariables',
}
